language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
sudo: false
install:
    - pip install tox
script:
    - tox
matrix:
    fast_finish: true
notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#django12factor"
        skip_join: true
        use_notice: true
