language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
sudo: false
env:
    - TOXENV=doc8
    - TOXENV=flake8
    - TOXENV=pep257
    - TOXENV=sphinx
    - TOXENV=mypy
install:
    - pip install tox
script:
    - tox -e $TOXENV
matrix:
    fast_finish: true
notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#django12factor"
        skip_join: true
        use_notice: true
